### ISSUE TITLE
WASM: Uncaught ReferenceError: Drag is not defined in dev console in pause menu

### ISSUE THREAD

**Issue by tjrileywisc** [phoboslab/wipeout-rewrite#80]
This is probably innocuous as it doesn't seem to do anything, but when I run the wasm build in Chrome I get this exception if I pause during a race:

```javascript
Uncaught ReferenceError: Drag is not defined
    at Object.P (klippy.js:87:45)
    at wrapper.extend.$owner (mootools-core.js:1367:23)
    at Object.execute (klippy.js:99:219)
    at wrapper.extend.$owner (mootools-core.js:1367:23)
    at Object.execute (klippy.js:9:413)
    at wrapper.extend.$owner (mootools-core.js:1367:23)
    at HTMLDocument.keyup (klippy.js:164:394)
    at wrapper.extend.$owner [as $caller] (mootools-core.js:1367:23)
    at HTMLDocument.defn (mootools-core.js:3970:20)
```

Not when I use Edge though.

**Comment by phoboslab** [comment]
We don't use mootools. This error is probably from a plugin you have installed in Chrome!?
